name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Connexion à Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yagenda-back:latest ./backend
      - name: Push des images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/yagenda-back:latest
